import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Seensd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }){
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased box-border w-full`}
      >
        <Header/>
        <div style={{paddingTop:'76px'}}></div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
